// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package workflow

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.DefinitionS3Location, b.ko.Spec.DefinitionS3Location) {
		delta.Add("Spec.DefinitionS3Location", a.ko.Spec.DefinitionS3Location, b.ko.Spec.DefinitionS3Location)
	} else if a.ko.Spec.DefinitionS3Location != nil && b.ko.Spec.DefinitionS3Location != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.DefinitionS3Location.Bucket, b.ko.Spec.DefinitionS3Location.Bucket) {
			delta.Add("Spec.DefinitionS3Location.Bucket", a.ko.Spec.DefinitionS3Location.Bucket, b.ko.Spec.DefinitionS3Location.Bucket)
		} else if a.ko.Spec.DefinitionS3Location.Bucket != nil && b.ko.Spec.DefinitionS3Location.Bucket != nil {
			if *a.ko.Spec.DefinitionS3Location.Bucket != *b.ko.Spec.DefinitionS3Location.Bucket {
				delta.Add("Spec.DefinitionS3Location.Bucket", a.ko.Spec.DefinitionS3Location.Bucket, b.ko.Spec.DefinitionS3Location.Bucket)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DefinitionS3Location.ObjectKey, b.ko.Spec.DefinitionS3Location.ObjectKey) {
			delta.Add("Spec.DefinitionS3Location.ObjectKey", a.ko.Spec.DefinitionS3Location.ObjectKey, b.ko.Spec.DefinitionS3Location.ObjectKey)
		} else if a.ko.Spec.DefinitionS3Location.ObjectKey != nil && b.ko.Spec.DefinitionS3Location.ObjectKey != nil {
			if *a.ko.Spec.DefinitionS3Location.ObjectKey != *b.ko.Spec.DefinitionS3Location.ObjectKey {
				delta.Add("Spec.DefinitionS3Location.ObjectKey", a.ko.Spec.DefinitionS3Location.ObjectKey, b.ko.Spec.DefinitionS3Location.ObjectKey)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DefinitionS3Location.VersionID, b.ko.Spec.DefinitionS3Location.VersionID) {
			delta.Add("Spec.DefinitionS3Location.VersionID", a.ko.Spec.DefinitionS3Location.VersionID, b.ko.Spec.DefinitionS3Location.VersionID)
		} else if a.ko.Spec.DefinitionS3Location.VersionID != nil && b.ko.Spec.DefinitionS3Location.VersionID != nil {
			if *a.ko.Spec.DefinitionS3Location.VersionID != *b.ko.Spec.DefinitionS3Location.VersionID {
				delta.Add("Spec.DefinitionS3Location.VersionID", a.ko.Spec.DefinitionS3Location.VersionID, b.ko.Spec.DefinitionS3Location.VersionID)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration) {
		delta.Add("Spec.EncryptionConfiguration", a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration)
	} else if a.ko.Spec.EncryptionConfiguration != nil && b.ko.Spec.EncryptionConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.KMSKeyID, b.ko.Spec.EncryptionConfiguration.KMSKeyID) {
			delta.Add("Spec.EncryptionConfiguration.KMSKeyID", a.ko.Spec.EncryptionConfiguration.KMSKeyID, b.ko.Spec.EncryptionConfiguration.KMSKeyID)
		} else if a.ko.Spec.EncryptionConfiguration.KMSKeyID != nil && b.ko.Spec.EncryptionConfiguration.KMSKeyID != nil {
			if *a.ko.Spec.EncryptionConfiguration.KMSKeyID != *b.ko.Spec.EncryptionConfiguration.KMSKeyID {
				delta.Add("Spec.EncryptionConfiguration.KMSKeyID", a.ko.Spec.EncryptionConfiguration.KMSKeyID, b.ko.Spec.EncryptionConfiguration.KMSKeyID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.Type, b.ko.Spec.EncryptionConfiguration.Type) {
			delta.Add("Spec.EncryptionConfiguration.Type", a.ko.Spec.EncryptionConfiguration.Type, b.ko.Spec.EncryptionConfiguration.Type)
		} else if a.ko.Spec.EncryptionConfiguration.Type != nil && b.ko.Spec.EncryptionConfiguration.Type != nil {
			if *a.ko.Spec.EncryptionConfiguration.Type != *b.ko.Spec.EncryptionConfiguration.Type {
				delta.Add("Spec.EncryptionConfiguration.Type", a.ko.Spec.EncryptionConfiguration.Type, b.ko.Spec.EncryptionConfiguration.Type)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration, b.ko.Spec.LoggingConfiguration) {
		delta.Add("Spec.LoggingConfiguration", a.ko.Spec.LoggingConfiguration, b.ko.Spec.LoggingConfiguration)
	} else if a.ko.Spec.LoggingConfiguration != nil && b.ko.Spec.LoggingConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.LoggingConfiguration.LogGroupName, b.ko.Spec.LoggingConfiguration.LogGroupName) {
			delta.Add("Spec.LoggingConfiguration.LogGroupName", a.ko.Spec.LoggingConfiguration.LogGroupName, b.ko.Spec.LoggingConfiguration.LogGroupName)
		} else if a.ko.Spec.LoggingConfiguration.LogGroupName != nil && b.ko.Spec.LoggingConfiguration.LogGroupName != nil {
			if *a.ko.Spec.LoggingConfiguration.LogGroupName != *b.ko.Spec.LoggingConfiguration.LogGroupName {
				delta.Add("Spec.LoggingConfiguration.LogGroupName", a.ko.Spec.LoggingConfiguration.LogGroupName, b.ko.Spec.LoggingConfiguration.LogGroupName)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfiguration, b.ko.Spec.NetworkConfiguration) {
		delta.Add("Spec.NetworkConfiguration", a.ko.Spec.NetworkConfiguration, b.ko.Spec.NetworkConfiguration)
	} else if a.ko.Spec.NetworkConfiguration != nil && b.ko.Spec.NetworkConfiguration != nil {
		if len(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs) != len(b.ko.Spec.NetworkConfiguration.SecurityGroupIDs) {
			delta.Add("Spec.NetworkConfiguration.SecurityGroupIDs", a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		} else if len(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs) {
				delta.Add("Spec.NetworkConfiguration.SecurityGroupIDs", a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
			}
		}
		if len(a.ko.Spec.NetworkConfiguration.SubnetIDs) != len(b.ko.Spec.NetworkConfiguration.SubnetIDs) {
			delta.Add("Spec.NetworkConfiguration.SubnetIDs", a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs)
		} else if len(a.ko.Spec.NetworkConfiguration.SubnetIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs) {
				delta.Add("Spec.NetworkConfiguration.SubnetIDs", a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoleARN, b.ko.Spec.RoleARN) {
		delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
	} else if a.ko.Spec.RoleARN != nil && b.ko.Spec.RoleARN != nil {
		if *a.ko.Spec.RoleARN != *b.ko.Spec.RoleARN {
			delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.RoleRef, b.ko.Spec.RoleRef) {
		delta.Add("Spec.RoleRef", a.ko.Spec.RoleRef, b.ko.Spec.RoleRef)
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TriggerMode, b.ko.Spec.TriggerMode) {
		delta.Add("Spec.TriggerMode", a.ko.Spec.TriggerMode, b.ko.Spec.TriggerMode)
	} else if a.ko.Spec.TriggerMode != nil && b.ko.Spec.TriggerMode != nil {
		if *a.ko.Spec.TriggerMode != *b.ko.Spec.TriggerMode {
			delta.Add("Spec.TriggerMode", a.ko.Spec.TriggerMode, b.ko.Spec.TriggerMode)
		}
	}

	return delta
}
