// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package workflow

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/mwaaserverless"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/mwaaserverless/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/mwaaserverless-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Workflow{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetWorkflowOutput
	resp, err = rm.sdkapi.GetWorkflow(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetWorkflow", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.DefinitionS3Location != nil {
		f1 := &svcapitypes.DefinitionS3Location{}
		if resp.DefinitionS3Location.Bucket != nil {
			f1.Bucket = resp.DefinitionS3Location.Bucket
		}
		if resp.DefinitionS3Location.ObjectKey != nil {
			f1.ObjectKey = resp.DefinitionS3Location.ObjectKey
		}
		if resp.DefinitionS3Location.VersionId != nil {
			f1.VersionID = resp.DefinitionS3Location.VersionId
		}
		ko.Spec.DefinitionS3Location = f1
	} else {
		ko.Spec.DefinitionS3Location = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.EncryptionConfiguration != nil {
		f3 := &svcapitypes.EncryptionConfiguration{}
		if resp.EncryptionConfiguration.KmsKeyId != nil {
			f3.KMSKeyID = resp.EncryptionConfiguration.KmsKeyId
		}
		if resp.EncryptionConfiguration.Type != "" {
			f3.Type = aws.String(string(resp.EncryptionConfiguration.Type))
		}
		ko.Spec.EncryptionConfiguration = f3
	} else {
		ko.Spec.EncryptionConfiguration = nil
	}
	if resp.LoggingConfiguration != nil {
		f4 := &svcapitypes.LoggingConfiguration{}
		if resp.LoggingConfiguration.LogGroupName != nil {
			f4.LogGroupName = resp.LoggingConfiguration.LogGroupName
		}
		ko.Spec.LoggingConfiguration = f4
	} else {
		ko.Spec.LoggingConfiguration = nil
	}
	if resp.ModifiedAt != nil {
		ko.Status.ModifiedAt = &metav1.Time{*resp.ModifiedAt}
	} else {
		ko.Status.ModifiedAt = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.NetworkConfiguration != nil {
		f7 := &svcapitypes.NetworkConfiguration{}
		if resp.NetworkConfiguration.SecurityGroupIds != nil {
			f7.SecurityGroupIDs = aws.StringSlice(resp.NetworkConfiguration.SecurityGroupIds)
		}
		if resp.NetworkConfiguration.SubnetIds != nil {
			f7.SubnetIDs = aws.StringSlice(resp.NetworkConfiguration.SubnetIds)
		}
		ko.Spec.NetworkConfiguration = f7
	} else {
		ko.Spec.NetworkConfiguration = nil
	}
	if resp.RoleArn != nil {
		ko.Spec.RoleARN = resp.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.ScheduleConfiguration != nil {
		f9 := &svcapitypes.ScheduleConfiguration{}
		if resp.ScheduleConfiguration.CronExpression != nil {
			f9.CronExpression = resp.ScheduleConfiguration.CronExpression
		}
		ko.Status.ScheduleConfiguration = f9
	} else {
		ko.Status.ScheduleConfiguration = nil
	}
	if resp.TriggerMode != nil {
		ko.Spec.TriggerMode = resp.TriggerMode
	} else {
		ko.Spec.TriggerMode = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.WorkflowArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.WorkflowArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.WorkflowStatus != "" {
		ko.Status.WorkflowStatus = aws.String(string(resp.WorkflowStatus))
	} else {
		ko.Status.WorkflowStatus = nil
	}
	if resp.WorkflowVersion != nil {
		ko.Status.WorkflowVersion = resp.WorkflowVersion
	} else {
		ko.Status.WorkflowVersion = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		tags, err := rm.getTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN))
		if err != nil {
			return nil, err
		}
		ko.Spec.Tags = tags
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return (r.ko.Status.ACKResourceMetadata == nil || r.ko.Status.ACKResourceMetadata.ARN == nil)

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetWorkflowInput, error) {
	res := &svcsdk.GetWorkflowInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.WorkflowArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Status.WorkflowVersion != nil {
		res.WorkflowVersion = r.ko.Status.WorkflowVersion
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateWorkflowOutput
	_ = resp
	resp, err = rm.sdkapi.CreateWorkflow(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateWorkflow", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.WorkflowArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.WorkflowArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.WorkflowStatus != "" {
		ko.Status.WorkflowStatus = aws.String(string(resp.WorkflowStatus))
	} else {
		ko.Status.WorkflowStatus = nil
	}
	if resp.WorkflowVersion != nil {
		ko.Status.WorkflowVersion = resp.WorkflowVersion
	} else {
		ko.Status.WorkflowVersion = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateWorkflowInput, error) {
	res := &svcsdk.CreateWorkflowInput{}

	if r.ko.Spec.DefinitionS3Location != nil {
		f1 := &svcsdktypes.DefinitionS3Location{}
		if r.ko.Spec.DefinitionS3Location.Bucket != nil {
			f1.Bucket = r.ko.Spec.DefinitionS3Location.Bucket
		}
		if r.ko.Spec.DefinitionS3Location.ObjectKey != nil {
			f1.ObjectKey = r.ko.Spec.DefinitionS3Location.ObjectKey
		}
		if r.ko.Spec.DefinitionS3Location.VersionID != nil {
			f1.VersionId = r.ko.Spec.DefinitionS3Location.VersionID
		}
		res.DefinitionS3Location = f1
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EncryptionConfiguration != nil {
		f3 := &svcsdktypes.EncryptionConfiguration{}
		if r.ko.Spec.EncryptionConfiguration.KMSKeyID != nil {
			f3.KmsKeyId = r.ko.Spec.EncryptionConfiguration.KMSKeyID
		}
		if r.ko.Spec.EncryptionConfiguration.Type != nil {
			f3.Type = svcsdktypes.EncryptionType(*r.ko.Spec.EncryptionConfiguration.Type)
		}
		res.EncryptionConfiguration = f3
	}
	if r.ko.Spec.LoggingConfiguration != nil {
		f4 := &svcsdktypes.LoggingConfiguration{}
		if r.ko.Spec.LoggingConfiguration.LogGroupName != nil {
			f4.LogGroupName = r.ko.Spec.LoggingConfiguration.LogGroupName
		}
		res.LoggingConfiguration = f4
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f6 := &svcsdktypes.NetworkConfiguration{}
		if r.ko.Spec.NetworkConfiguration.SecurityGroupIDs != nil {
			f6.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		}
		if r.ko.Spec.NetworkConfiguration.SubnetIDs != nil {
			f6.SubnetIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SubnetIDs)
		}
		res.NetworkConfiguration = f6
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}
	if r.ko.Spec.TriggerMode != nil {
		res.TriggerMode = r.ko.Spec.TriggerMode
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	// Tags are managed via TagResource/UntagResource, not UpdateWorkflow. Sync
	// any tag drift here so the resource doesn't reconcile forever.
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}
	// If ONLY tags changed there is nothing for UpdateWorkflow to do, so
	// short-circuit and return the desired state.
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateWorkflowOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateWorkflow(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateWorkflow", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ModifiedAt != nil {
		ko.Status.ModifiedAt = &metav1.Time{*resp.ModifiedAt}
	} else {
		ko.Status.ModifiedAt = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.WorkflowArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.WorkflowArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.WorkflowVersion != nil {
		ko.Status.WorkflowVersion = resp.WorkflowVersion
	} else {
		ko.Status.WorkflowVersion = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateWorkflowInput, error) {
	res := &svcsdk.UpdateWorkflowInput{}

	if r.ko.Spec.DefinitionS3Location != nil {
		f0 := &svcsdktypes.DefinitionS3Location{}
		if r.ko.Spec.DefinitionS3Location.Bucket != nil {
			f0.Bucket = r.ko.Spec.DefinitionS3Location.Bucket
		}
		if r.ko.Spec.DefinitionS3Location.ObjectKey != nil {
			f0.ObjectKey = r.ko.Spec.DefinitionS3Location.ObjectKey
		}
		if r.ko.Spec.DefinitionS3Location.VersionID != nil {
			f0.VersionId = r.ko.Spec.DefinitionS3Location.VersionID
		}
		res.DefinitionS3Location = f0
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.LoggingConfiguration != nil {
		f2 := &svcsdktypes.LoggingConfiguration{}
		if r.ko.Spec.LoggingConfiguration.LogGroupName != nil {
			f2.LogGroupName = r.ko.Spec.LoggingConfiguration.LogGroupName
		}
		res.LoggingConfiguration = f2
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f3 := &svcsdktypes.NetworkConfiguration{}
		if r.ko.Spec.NetworkConfiguration.SecurityGroupIDs != nil {
			f3.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		}
		if r.ko.Spec.NetworkConfiguration.SubnetIDs != nil {
			f3.SubnetIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SubnetIDs)
		}
		res.NetworkConfiguration = f3
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.TriggerMode != nil {
		res.TriggerMode = r.ko.Spec.TriggerMode
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.WorkflowArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// DeleteWorkflow deletes only the specified version when WorkflowVersion is
	// set; leaving it unset deletes the workflow entirely. ACK owns the whole
	// workflow, so never scope the delete to a single version -- otherwise the
	// API returns success, ACK removes the finalizer and reports the CR
	// deleted, but the real workflow stays READY in AWS (resource leak).
	input.WorkflowVersion = nil

	var resp *svcsdk.DeleteWorkflowOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteWorkflow(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteWorkflow", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteWorkflowInput, error) {
	res := &svcsdk.DeleteWorkflowInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.WorkflowArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Status.WorkflowVersion != nil {
		res.WorkflowVersion = r.ko.Status.WorkflowVersion
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Workflow,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
