// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type EncryptionType string

const (
	EncryptionType_AWS_MANAGED_KEY      EncryptionType = "AWS_MANAGED_KEY"
	EncryptionType_CUSTOMER_MANAGED_KEY EncryptionType = "CUSTOMER_MANAGED_KEY"
)

type RunType string

const (
	RunType_ON_DEMAND RunType = "ON_DEMAND"
	RunType_SCHEDULED RunType = "SCHEDULED"
)

type TaskInstanceStatus string

const (
	TaskInstanceStatus_CANCELLED         TaskInstanceStatus = "CANCELLED"
	TaskInstanceStatus_DEFERRED          TaskInstanceStatus = "DEFERRED"
	TaskInstanceStatus_FAILED            TaskInstanceStatus = "FAILED"
	TaskInstanceStatus_NONE              TaskInstanceStatus = "NONE"
	TaskInstanceStatus_QUEUED            TaskInstanceStatus = "QUEUED"
	TaskInstanceStatus_REMOVED           TaskInstanceStatus = "REMOVED"
	TaskInstanceStatus_RESTARTING        TaskInstanceStatus = "RESTARTING"
	TaskInstanceStatus_RUNNING           TaskInstanceStatus = "RUNNING"
	TaskInstanceStatus_SCHEDULED         TaskInstanceStatus = "SCHEDULED"
	TaskInstanceStatus_SUCCESS           TaskInstanceStatus = "SUCCESS"
	TaskInstanceStatus_TIMEOUT           TaskInstanceStatus = "TIMEOUT"
	TaskInstanceStatus_UPSTREAM_FAILED   TaskInstanceStatus = "UPSTREAM_FAILED"
	TaskInstanceStatus_UP_FOR_RESCHEDULE TaskInstanceStatus = "UP_FOR_RESCHEDULE"
	TaskInstanceStatus_UP_FOR_RETRY      TaskInstanceStatus = "UP_FOR_RETRY"
)

type ValidationExceptionReason string

const (
	ValidationExceptionReason_cannotParse           ValidationExceptionReason = "cannotParse"
	ValidationExceptionReason_fieldValidationFailed ValidationExceptionReason = "fieldValidationFailed"
	ValidationExceptionReason_other                 ValidationExceptionReason = "other"
	ValidationExceptionReason_unknownOperation      ValidationExceptionReason = "unknownOperation"
)

type WorkflowRunStatus string

const (
	WorkflowRunStatus_FAILED   WorkflowRunStatus = "FAILED"
	WorkflowRunStatus_QUEUED   WorkflowRunStatus = "QUEUED"
	WorkflowRunStatus_RUNNING  WorkflowRunStatus = "RUNNING"
	WorkflowRunStatus_STARTING WorkflowRunStatus = "STARTING"
	WorkflowRunStatus_STOPPED  WorkflowRunStatus = "STOPPED"
	WorkflowRunStatus_STOPPING WorkflowRunStatus = "STOPPING"
	WorkflowRunStatus_SUCCESS  WorkflowRunStatus = "SUCCESS"
	WorkflowRunStatus_TIMEOUT  WorkflowRunStatus = "TIMEOUT"
)

type WorkflowStatus_SDK string

const (
	WorkflowStatus_SDK_DELETING WorkflowStatus_SDK = "DELETING"
	WorkflowStatus_SDK_READY    WorkflowStatus_SDK = "READY"
)
