// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WorkflowSpec defines the desired state of Workflow.
type WorkflowSpec struct {

	// The Amazon S3 location where the workflow definition file is stored. This
	// must point to a valid YAML file that defines the workflow structure using
	// supported Amazon Web Services operators and tasks. Amazon Managed Workflows
	// for Apache Airflow Serverless takes a snapshot of the definition at creation
	// time, so subsequent changes to the Amazon S3 object will not affect the workflow
	// unless you create a new version. In your YAML definition, include task dependencies,
	// scheduling information, and operator configurations that are compatible with
	// the Amazon Managed Workflows for Apache Airflow Serverless execution environment.
	// +kubebuilder:validation:Required
	DefinitionS3Location *DefinitionS3Location `json:"definitionS3Location"`
	// An optional description of the workflow that you can use to provide additional
	// context about the workflow's purpose and functionality.
	//
	// Regex Pattern: `^.+$`
	Description *string `json:"description,omitempty"`
	// The configuration for encrypting workflow data at rest and in transit. Specifies
	// the encryption type and optional KMS key for customer-managed encryption.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	EncryptionConfiguration *EncryptionConfiguration `json:"encryptionConfiguration,omitempty"`
	// The configuration for workflow logging. Specifies the CloudWatch log group
	// where workflow execution logs are stored. Amazon Managed Workflows for Apache
	// Airflow Serverless automatically exports worker logs and task-level information
	// to the specified log group in your account using remote logging functionality.
	// This provides comprehensive observability for debugging and monitoring workflow
	// execution across the distributed, serverless environment.
	LoggingConfiguration *LoggingConfiguration `json:"loggingConfiguration,omitempty"`
	// The name of the workflow. You must use unique workflow names within your
	// Amazon Web Services account. The service generates a unique identifier that
	// is appended to ensure temporal uniqueness across the account lifecycle.
	//
	// Regex Pattern: `^[a-zA-Z0-9]+[a-zA-Z0-9\.\-_]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Network configuration for the workflow execution environment, including VPC
	// security groups and subnets for secure network access. When specified, Amazon
	// Managed Workflows for Apache Airflow Serverless deploys ECS worker tasks
	// in your customer VPC to provide secure connectivity to your resources. If
	// not specified, tasks run in the service's default worker VPC with network
	// isolation from other customers. This configuration enables secure access
	// to VPC-only resources like RDS databases or private endpoints.
	NetworkConfiguration *NetworkConfiguration `json:"networkConfiguration,omitempty"`
	// The Amazon Resource Name (ARN) of the IAM role that Amazon Managed Workflows
	// for Apache Airflow Serverless assumes when executing the workflow. This role
	// must have the necessary permissions to access the required Amazon Web Services
	// services and resources that your workflow tasks will interact with. The role
	// is used for task execution in the isolated, multi-tenant environment and
	// should follow the principle of least privilege. Amazon Managed Workflows
	// for Apache Airflow Serverless validates role access during workflow creation
	// but runtime permission checks are performed by the target services.
	//
	// Regex Pattern: `^arn:aws(?:-(?:cn|us-gov|iso|iso-b|iso-e|iso-f))?:iam::[0-9]{12}:role(/[a-zA-Z0-9+=,.@_\-]{1,512})*?/[a-zA-Z0-9+=,.@_\-]{1,64}$`
	RoleARN *string                                  `json:"roleARN,omitempty"`
	RoleRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"roleRef,omitempty"`
	// A map of tags to assign to the workflow resource. Tags are key-value pairs
	// that are used for resource organization and cost allocation.
	Tags map[string]*string `json:"tags,omitempty"`
	// The trigger mode for the workflow execution.
	//
	// Regex Pattern: `^.*$`
	TriggerMode *string `json:"triggerMode,omitempty"`
}

// WorkflowStatus defines the observed state of Workflow
type WorkflowStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the workflow was created, in ISO 8601 date-time format.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The timestamp when the workflow was last modified, in ISO 8601 date-time
	// format.
	// +kubebuilder:validation:Optional
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// The schedule configuration for the workflow, including cron expressions for
	// automated execution. Amazon Managed Workflows for Apache Airflow Serverless
	// uses EventBridge Scheduler for cost-effective, timezone-aware scheduling.
	// When a workflow includes schedule information in its YAML definition, the
	// service automatically configures the appropriate triggers for automated execution.
	// Only one version of a workflow can have an active schedule at any given time.
	// +kubebuilder:validation:Optional
	ScheduleConfiguration *ScheduleConfiguration `json:"scheduleConfiguration,omitempty"`
	// The current status of the workflow. Possible values are READY (workflow is
	// ready to run) and DELETING (workflow is being deleted).
	// +kubebuilder:validation:Optional
	WorkflowStatus *string `json:"status,omitempty"`
	// The version identifier of the workflow. This is a service-generated alphanumeric
	// string that uniquely identifies this version of the workflow. Amazon Managed
	// Workflows for Apache Airflow Serverless uses a version-first approach where
	// each workflow can have multiple immutable versions, which allows you to maintain
	// different configurations and roll back to previous versions as needed. The
	// version identifier is used in ARNs and API operations to reference specific
	// workflow versions.
	//
	// Regex Pattern: `^[a-z0-9]{32}$`
	// +kubebuilder:validation:Optional
	WorkflowVersion *string `json:"version,omitempty"`
}

// Workflow is the Schema for the Workflows API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="STATUS",type=string,priority=0,JSONPath=`.status.status`
// +kubebuilder:printcolumn:name="VERSION",type=string,priority=0,JSONPath=`.status.version`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",priority=0,JSONPath=".metadata.creationTimestamp"
type Workflow struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WorkflowSpec   `json:"spec,omitempty"`
	Status            WorkflowStatus `json:"status,omitempty"`
}

// WorkflowList contains a list of Workflow
// +kubebuilder:object:root=true
type WorkflowList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Workflow `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Workflow{}, &WorkflowList{})
}
